import { Container, Box, Text, Flex, IconButton } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { MainLayout } from '@todocity/ui';
import { LightDarkButton } from '@todocity/components';

function Header() {
  return (
    <Flex p="2">
      <Text variant="h1" flex="1">
        TODOCITY
      </Text>
      <Flex>
        <Text variant="navigation">Early Pricing</Text>
        <LightDarkButton />
      </Flex>
    </Flex>
  );
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Welcome to TodoCity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Header />
        <Flex flex={1} alignItems="center">
          <Box flex={3}>
            <Text variant="hero">Your New Favorite Todo App</Text>
            <Text variant="bodyBig">
              Complete your Todos. Get points. Build your city.
            </Text>
          </Box>
          <Box flex={2}></Box>
        </Flex>
      </MainLayout>
    </>
  );
};

export default Home;
