import { Text, Box, Flex } from '@todocity/ui';
import { AnalButton, MainLayout } from '@todocity/components';
import type { NextPage } from 'next';
import Link from 'next/link';
import Head from 'next/head';
import { Suspense, useRef } from 'react';
import dynamic from 'next/dynamic';
import { eventTriggers } from '@todocity/analytics';
import { useAuthState } from 'react-firebase-hooks/auth';
import { auth } from '@todocity/firebase';
import { IconArrowRight } from '@tabler/icons';
const HomeScene = dynamic(() => import('../libs/todocity/three/index'), {
  suspense: true,
});

const Home: NextPage = () => {
  const [user, loading] = useAuthState(auth);
  const mainRef = useRef<HTMLDivElement>(null!);

  return (
    <>
      <Head>
        <title>Welcome to TodoCity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main ref={mainRef}>
        <MainLayout>
          <Flex flex={1} alignItems="center">
            <Box flex={3}>
              <Text as="h1" variant="hero">
                Your New Favorite Todo App
              </Text>
              <Text as="h2" variant="h2" color="gray.600" pb={24}>
                Complete your Todos. Get points. Build your city.
              </Text>
              <Box width="max-content">
                <Link href={user ? '/city' : '/signup'}>
                  <AnalButton
                    variant="primary"
                    size="xl"
                    mb="2"
                    isLoading={loading}
                    analytics={{ buttonName: eventTriggers.MAIN_CTA }}
                  >
                    {user ? (
                      <>
                        Go to Your City <IconArrowRight />
                      </>
                    ) : (
                      'Create your city'
                    )}
                  </AnalButton>
                </Link>
                <Text textAlign="center" color="gray.600">
                  Your todo city is free forever
                </Text>
              </Box>
            </Box>
            <Box flex={2} height="100%">
              <Suspense fallback={null}>
                <HomeScene />
              </Suspense>
            </Box>
          </Flex>
        </MainLayout>
      </main>
    </>
  );
};

export default Home;
